spring.datasource.url=jdbc:postgresql://db.aofaofkebqmsjjvegdcc.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Dharani_@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080